import { Link } from 'react-router-dom';

type PolicyKey = 'terms' | 'privacy' | 'refund';

const policies: Record<PolicyKey, { title: string; updated: string; body: string }> = {
  terms: {
    title: 'Terms & Conditions',
    updated: 'Effective for Pluto users',
    body: `This document is an electronic record in terms of the Information Technology Act, 2000 and the rules thereunder as applicable, and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.

This document is published in accordance with Rule 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011, which requires publishing the rules and regulations, privacy policy, and terms of use for access or usage of https://pluto.akcero.ai, including the related mobile site and mobile application, collectively referred to as the Platform.

The Platform is owned by AKCERO PRIVATE LIMITED, a company incorporated under the Companies Act, 1956 with its registered office at K1201 Rainbow Vistas Rock Garden Greenhills Road Moosapet Balanagar, hereinafter referred to as Platform Owner, we, us, or our.

Your use of the Platform, services, and tools is governed by these terms and conditions as applicable to the Platform, including the applicable policies incorporated by reference. If you transact on the Platform, you shall be subject to the policies applicable to such transaction. By using the Platform, you contract with the Platform Owner, and these terms and policies constitute your binding obligations.

These Terms of Use relate to your use of our website, goods, or services, collectively referred to as Services. Any terms proposed by you that are in addition to or conflict with these Terms of Use are expressly rejected by the Platform Owner and shall have no force or effect. These Terms of Use may be modified at any time without assigning any reason. It is your responsibility to periodically review them.

For these Terms of Use, wherever the context requires, you, your, or user means any natural or legal person who has agreed to become a user or buyer on the Platform.

Accessing, browsing, or otherwise using the Platform indicates your agreement to all terms and conditions under these Terms of Use. Please read them carefully before proceeding.

To access and use the Services, you agree to provide true, accurate, and complete information during and after registration. You are responsible for all acts done through your registered account on the Platform.

Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness, or suitability of information and materials offered on this website or through the Services for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors, and we expressly exclude liability for such inaccuracies or errors to the fullest extent permitted by law.

Your use of our Services and the Platform is solely at your own risk and discretion. You are required to independently assess and ensure that the Services meet your requirements.

The contents of the Platform and the Services are proprietary to us and licensed to us. You do not have authority to claim intellectual property rights, title, or interest in the contents, including design, layout, look, and graphics.

You acknowledge that unauthorized use of the Platform or Services may lead to action against you under these Terms of Use or applicable laws.

You agree to pay us the charges associated with availing the Services.

You agree not to use the Platform or Services for any purpose that is unlawful, illegal, or forbidden by these Terms, Indian law, or local laws that may apply to you.

You agree and acknowledge that the website and Services may contain links to third-party websites. On accessing those links, you will be governed by the terms of use, privacy policy, and other policies of such third-party websites. These links are provided for your convenience and further information.

You understand that upon initiating a transaction for availing the Services, you enter into a legally binding and enforceable contract with the Platform Owner for the Services.

You shall indemnify and hold harmless the Platform Owner, its affiliates, group companies where applicable, and their respective officers, directors, agents, and employees from any claim, demand, action, reasonable attorney fees, or penalty imposed due to or arising out of your breach of these Terms of Use, Privacy Policy, other policies, laws, rules, regulations, or third-party rights including intellectual property rights.

Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for failure to perform an obligation if performance is prevented or delayed by a force majeure event.

These Terms and any dispute or claim relating to them or their enforceability shall be governed by and construed in accordance with the laws of India.

All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the competent courts in India.

All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website.`,
  },
  privacy: {
    title: 'Privacy Policy',
    updated: 'Effective for Pluto users',
    body: `This Privacy Policy describes how AKCERO PRIVATE LIMITED and its affiliates, collectively referred to as AKCERO PRIVATE LIMITED, we, our, or us, collect, use, share, protect, or otherwise process your personal data through https://pluto.akcero.ai, hereinafter referred to as the Platform.

You may be able to browse certain sections of the Platform without registering with us. We do not offer any product or service under this Platform outside India, and your personal data will primarily be stored and processed in India.

By visiting this Platform, providing your information, or availing any product or service offered on the Platform, you expressly agree to be bound by this Privacy Policy, the Terms of Use, and applicable service or product terms and conditions. You also agree to be governed by the laws of India, including laws applicable to data protection and privacy. If you do not agree, please do not use or access our Platform.

We collect your personal data when you use our Platform, services, or otherwise interact with us during the course of our relationship. Information collected may include personal data provided during sign-up, registration, or Platform usage, such as name, date of birth, address, telephone or mobile number, email ID, and information shared as proof of identity or address.

Sensitive personal data may be collected with your consent, such as bank account information, credit or debit card details, other payment instrument information, biometric information, facial features, or physiological information where such features are opted for and available on the Platform, all in accordance with applicable laws.

You always have the option not to provide information by choosing not to use a particular service or feature on the Platform. We may track your behaviour, preferences, and other information you choose to provide on the Platform. This information may be compiled and analysed on an aggregated basis.

We may collect information related to your transactions on the Platform and third-party business partner platforms. When a third-party business partner collects your personal data directly from you, you will be governed by their privacy policies. We are not responsible for such third-party privacy practices or content, and we request that you read their privacy policies before disclosing information.

If you receive an email or call from a person or association claiming to be AKCERO PRIVATE LIMITED and seeking sensitive personal data such as debit or credit card PIN, net-banking password, or mobile banking password, please never provide such information. If you have already revealed such information, report it immediately to an appropriate law enforcement agency.

We use personal data to provide the services you request. To the extent we use your personal data for marketing, we will provide the ability to opt out. We use personal data to assist sellers and business partners in handling and fulfilling orders, enhancing customer experience, resolving disputes, troubleshooting problems, informing you about offers, products, services, and updates, customizing your experience, detecting and protecting against error, fraud, and criminal activity, enforcing terms and conditions, conducting marketing research, analysis, and surveys, and as otherwise described at the time of collection.

You understand that access to certain products or services may be affected if required permissions are not provided.

We may share personal data internally within our group entities, corporate entities, and affiliates to provide access to services and products offered by them. These entities and affiliates may market to you as a result of such sharing unless you explicitly opt out.

We may disclose personal data to third parties such as sellers, business partners, service providers, logistics partners, prepaid payment instrument issuers, third-party reward programs, and other payment options selected by you. Such disclosure may be required to provide access to services and products, comply with legal obligations, enforce user agreements, facilitate marketing and advertising, and prevent, detect, mitigate, or investigate fraudulent or illegal activities.

We may disclose personal and sensitive personal data to government agencies or authorised law enforcement agencies if required by law or in good faith belief that disclosure is reasonably necessary to respond to subpoenas, court orders, or legal process. We may also disclose personal data to law enforcement offices, third-party rights owners, or others in good faith where necessary to enforce Terms of Use or Privacy Policy, respond to claims, or protect the rights, property, or safety of users or the public.

To protect personal data from unauthorised access, disclosure, loss, or misuse, we adopt reasonable security practices and procedures. Once information is in our possession or whenever you access your account information, we follow security guidelines to protect it against unauthorised access and offer secure server usage where applicable.

However, transmission of information is not completely secure for reasons beyond our control. By using the Platform, you accept the security implications of data transmission over the internet and World Wide Web, which cannot always be guaranteed as completely secure. Users are responsible for protecting login and password records for their accounts.

You may delete your account by visiting your profile and settings on the Platform. This action may result in losing all information related to your account. You may also write to us using the contact information provided below for assistance with such requests.

We may refuse or delay account deletion in the event of any pending grievance, claim, shipment, or service. Once an account is deleted, you will lose access to it. We retain personal data no longer than required for the purpose for which it was collected or as required by applicable law. However, we may retain data where necessary to prevent fraud or future abuse, or for other legitimate purposes. We may retain anonymised data for analytical and research purposes.

You may access, rectify, and update your personal data through the functionalities provided on the Platform.

By visiting the Platform or providing your information, you consent to collection, use, storage, disclosure, and processing of your information in accordance with this Privacy Policy. If you disclose personal data relating to other people, you represent that you have authority to do so and permit us to use it in accordance with this Privacy Policy.

You consent to us, including corporate entities, affiliates, lending partners, technology partners, marketing channels, business partners, and other third parties, contacting you through SMS, instant messaging apps, calls, or email for the purposes specified in this Privacy Policy.

You may withdraw consent by writing to the Grievance Officer using the contact information provided below. Please mention "Withdrawal of consent for processing personal data" in the subject line. We may verify such requests before acting on them. Withdrawal of consent will not be retrospective and will be handled in accordance with the Terms of Use, this Privacy Policy, and applicable laws. If consent is withdrawn, we reserve the right to restrict or deny services for which we consider such information necessary.

Please check this Privacy Policy periodically for changes. We may update it to reflect changes to information practices and may notify you about significant changes in the manner required under applicable laws.

Grievance Officer details, designation, company address, contact phone, and support hours will be provided through the Platform contact information.`,
  },
  refund: {
    title: 'Refund and Cancellation Policy',
    updated: 'Effective for Pluto users',
    body: `This refund and cancellation policy outlines how you can cancel or seek a refund for a product or service purchased through the Platform.

Cancellations will only be considered if the request is made within 7 days of placing the order. However, cancellation requests may not be entertained if orders have been communicated to sellers or merchants listed on the Platform and they have initiated shipping, or if the product is out for delivery. In such an event, you may choose to reject the product at the doorstep.

AKCERO PRIVATE LIMITED does not accept cancellation requests for perishable items such as flowers or eatables. However, refund or replacement may be made if the user establishes that the quality of the delivered product is not good.

In case of receipt of damaged or defective items, please report the issue to our customer service team. The request will be entertained once the seller or merchant listed on the Platform has checked and determined the issue at its own end. This should be reported within 7 days of receipt of products.

If you feel that the product received is not as shown on the site or as per your expectations, you must bring it to the notice of our customer service within 7 days of receiving the product. The customer service team will review your complaint and take an appropriate decision.

For complaints regarding products that come with manufacturer warranties, please refer the issue to the manufacturer.

If any refund is approved by AKCERO PRIVATE LIMITED, it will take 7 days for the refund to be processed.

Return Policy

We offer refund or exchange within the first 7 days from the date of purchase. If 7 days have passed since your purchase, you will not be offered a return, exchange, or refund of any kind.

To be eligible for a return or exchange, the purchased item should be unused and in the same condition as received, and the item must have original packaging. If an item was purchased on sale, it may not be eligible for return or exchange. Only items found defective or damaged may be replaced based on an exchange request.

There may be categories of products or items exempted from returns or refunds. Such categories will be identified to you at the time of purchase.

For accepted exchange or return requests, once the returned product or item is received and inspected by us, we will send an email notifying you about receipt of the returned or exchanged product. If approved after quality check, the return or exchange request will be processed in accordance with our policies.

Shipping Policy

Orders for users are shipped through registered domestic courier companies or speed post only. Orders are shipped within 7 days from the date of order and payment, or as per the delivery date agreed at the time of order confirmation and delivery of the shipment, subject to courier company or post office norms.

The Platform Owner shall not be liable for delay in delivery by the courier company or postal authority. Delivery of all orders will be made to the address provided by the buyer at the time of purchase. Delivery of our services will be confirmed on the email ID specified at the time of registration.

If any shipping costs are levied by the seller or the Platform Owner, as applicable, such costs are not refundable.`,
  },
};

export const PolicyPage = ({ type }: { type: PolicyKey }) => {
  const policy = policies[type];

  return (
    <main style={{ minHeight: '100vh', background: 'var(--background)', color: 'var(--foreground)', padding: '48px 20px' }}>
      <section style={{ maxWidth: '960px', margin: '0 auto' }}>
        <Link to="/" style={{ color: 'var(--primary)', textDecoration: 'none', fontWeight: 700 }}>
          Back to Pluto
        </Link>

        <header style={{ marginTop: '44px', marginBottom: '28px' }}>
          <p style={{ color: 'var(--text-secondary)', fontSize: '0.82rem', fontWeight: 700, letterSpacing: '0.08em', textTransform: 'uppercase', marginBottom: '12px' }}>
            {policy.updated}
          </p>
          <h1 style={{ fontSize: 'clamp(1.1rem, 3vw, 2.3rem)', lineHeight: 1, letterSpacing: '-0.03em', margin: 0 }}>
            {policy.title}
          </h1>
        </header>

        <article
          className="glass-card"
          style={{
            padding: 'clamp(24px, 5vw, 48px)',
            borderRadius: '16px',
            display: 'flex',
            flexDirection: 'column',
            gap: '18px',
          }}
        >
          {policy.body.split('\n\n').map((paragraph) => {
            const isSectionHeading = !paragraph.includes('.') && paragraph.length < 80;

            return isSectionHeading ? (
              <h2 key={paragraph} style={{ fontSize: '1.4rem', margin: '18px 0 0', color: 'var(--primary)' }}>
                {paragraph}
              </h2>
            ) : (
              <p key={paragraph} style={{ margin: 0, color: 'var(--text-secondary)', lineHeight: 1.8, fontSize: '0.98rem' }}>
                {paragraph}
              </p>
            );
          })}
        </article>
      </section>
    </main>
  );
};
