import { Link } from 'react-router-dom';

type PolicyKey = 'terms' | 'privacy' | 'refund';

const policies: Record<PolicyKey, { title: string; updated: string; body: string }> = {
  terms: {
    title: 'Terms & Conditions',
    updated: 'Effective for Pluto users',
    body: `This document is an electronic record in terms of the Information Technology Act, 2000 and the rules thereunder as applicable, and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.

This document is published in accordance with Rule 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011, which requires publishing the rules and regulations, privacy policy, and terms of use for access or usage of https://pluto.akcero.ai, including the related mobile site and mobile application, collectively referred to as the Platform.

The Platform is owned by AKCERO PRIVATE LIMITED, a company incorporated under the Companies Act, 1956 with its registered office at K1201 Rainbow Vistas Rock Garden Greenhills Road Moosapet Balanagar, hereinafter referred to as Platform Owner, we, us, or our.

Your use of the Platform, services, and tools is governed by these terms and conditions as applicable to the Platform, including the applicable policies incorporated by reference. If you transact on the Platform, you shall be subject to the policies applicable to such transaction. By using the Platform, you contract with the Platform Owner, and these terms and policies constitute your binding obligations.

These Terms of Use relate to your use of our website, goods, or services, collectively referred to as Services. Any terms proposed by you that are in addition to or conflict with these Terms of Use are expressly rejected by the Platform Owner and shall have no force or effect. These Terms of Use may be modified at any time without assigning any reason. It is your responsibility to periodically review them.

For these Terms of Use, wherever the context requires, you, your, or user means any natural or legal person who has agreed to become a user or buyer on the Platform.

Accessing, browsing, or otherwise using the Platform indicates your agreement to all terms and conditions under these Terms of Use. Please read them carefully before proceeding.

To access and use the Services, you agree to provide true, accurate, and complete information during and after registration. You are responsible for all acts done through your registered account on the Platform.

Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness, or suitability of information and materials offered on this website or through the Services for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors, and we expressly exclude liability for such inaccuracies or errors to the fullest extent permitted by law.

Your use of our Services and the Platform is solely at your own risk and discretion. You are required to independently assess and ensure that the Services meet your requirements.

The contents of the Platform and the Services are proprietary to us and licensed to us. You do not have authority to claim intellectual property rights, title, or interest in the contents, including design, layout, look, and graphics.

You acknowledge that unauthorized use of the Platform or Services may lead to action against you under these Terms of Use or applicable laws.

You agree to pay us the charges associated with availing the Services.

You agree not to use the Platform or Services for any purpose that is unlawful, illegal, or forbidden by these Terms, Indian law, or local laws that may apply to you.

You agree and acknowledge that the website and Services may contain links to third-party websites. On accessing those links, you will be governed by the terms of use, privacy policy, and other policies of such third-party websites. These links are provided for your convenience and further information.

You understand that upon initiating a transaction for availing the Services, you enter into a legally binding and enforceable contract with the Platform Owner for the Services.

You shall indemnify and hold harmless the Platform Owner, its affiliates, group companies where applicable, and their respective officers, directors, agents, and employees from any claim, demand, action, reasonable attorney fees, or penalty imposed due to or arising out of your breach of these Terms of Use, Privacy Policy, other policies, laws, rules, regulations, or third-party rights including intellectual property rights.

Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for failure to perform an obligation if performance is prevented or delayed by a force majeure event.

These Terms and any dispute or claim relating to them or their enforceability shall be governed by and construed in accordance with the laws of India.

All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the competent courts in India.

All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website.`,
  },
  privacy: {
    title: 'Privacy Policy',
    updated: 'Effective for Pluto users',
    body: `This Privacy Policy describes how AKCERO PRIVATE LIMITED, doing business through Pluto, collects, uses, stores, and shares personal data when you use https://pluto.akcero.ai and related Pluto services.

We primarily collect account information you provide directly, such as your email address, display name, education level, learning objective, and authentication details managed through Firebase Authentication.

When you use Pluto chat features, we store your conversation data, including messages, conversation summaries used for continuity, and related metadata such as timestamps, mode selection, and thread or project labels.

When you upload images or documents in chat, the file content is sent directly to our AI provider for processing and is not stored on our servers. Only metadata (filename, file type, size) is retained as part of your chat history.

If you subscribe to a paid plan, we store subscription and billing records needed to manage your plan. This includes plan status, payment references, transaction records, and Razorpay subscription metadata. Pluto does not collect or store your full card number, card PIN, or banking password in its own database.

We also store product usage data needed to run the service, such as daily quota usage, token consumption, request logs, and support or abuse-prevention records.

We use essential cookies and browser local storage to keep you signed in, preserve core Pluto state such as chat continuity and consent preferences, and support essential reliability monitoring needed to detect and fix production issues.

We use this information to create and secure your account, provide Pluto's tutoring features, personalize responses based on your selected education level and learning objective, enforce plan limits, process subscription events, respond to support issues, and improve reliability and safety.

We may share limited data with service providers that help us operate Pluto, such as Firebase and Google Cloud for authentication, database, hosting, and logging, Amazon Bedrock and Google Gemini for AI model responses, Razorpay for subscription billing, and Resend for transactional emails. Those providers process data only as needed to deliver the service.

We may also disclose information where required by law, to respond to valid legal requests, to investigate fraud or abuse, or to protect the rights, safety, and property of Pluto, our users, or the public.

We use reasonable technical and organizational safeguards to protect your data, but no internet-based service can guarantee absolute security. You are responsible for protecting access to your account credentials and devices.

You can access and update parts of your profile through the Pluto application. We may retain limited records where required for legal, billing, fraud-prevention, or dispute-resolution purposes.

We retain personal data only for as long as it is needed to operate Pluto, meet legal or billing obligations, prevent abuse, resolve disputes, or maintain necessary audit trails. We may keep aggregated or anonymized usage information for analytics and product improvement.

Pluto may update this Privacy Policy from time to time. Continued use of the Platform after an update means you accept the revised policy. If changes are material, we may provide additional notice through the Platform or by email where appropriate.

If you have questions about this Privacy Policy, please use the contact information provided on the Platform.`,
  },
  refund: {
    title: 'Refund and Cancellation Policy',
    updated: 'Effective for Pluto users',
    body: `This refund and cancellation policy outlines how you can cancel or seek a refund for a product or service purchased through the Platform.

Cancellations will only be considered if the request is made within 7 days of placing the order. However, cancellation requests may not be entertained if orders have been communicated to sellers or merchants listed on the Platform and they have initiated shipping, or if the product is out for delivery. In such an event, you may choose to reject the product at the doorstep.

AKCERO PRIVATE LIMITED does not accept cancellation requests for perishable items such as flowers or eatables. However, refund or replacement may be made if the user establishes that the quality of the delivered product is not good.

In case of receipt of damaged or defective items, please report the issue to our customer service team. The request will be entertained once the seller or merchant listed on the Platform has checked and determined the issue at its own end. This should be reported within 7 days of receipt of products.

If you feel that the product received is not as shown on the site or as per your expectations, you must bring it to the notice of our customer service within 7 days of receiving the product. The customer service team will review your complaint and take an appropriate decision.

For complaints regarding products that come with manufacturer warranties, please refer the issue to the manufacturer.

If any refund is approved by AKCERO PRIVATE LIMITED, it will take 7 days for the refund to be processed.

Return Policy

We offer refund or exchange within the first 7 days from the date of purchase. If 7 days have passed since your purchase, you will not be offered a return, exchange, or refund of any kind.

To be eligible for a return or exchange, the purchased item should be unused and in the same condition as received, and the item must have original packaging. If an item was purchased on sale, it may not be eligible for return or exchange. Only items found defective or damaged may be replaced based on an exchange request.

There may be categories of products or items exempted from returns or refunds. Such categories will be identified to you at the time of purchase.

For accepted exchange or return requests, once the returned product or item is received and inspected by us, we will send an email notifying you about receipt of the returned or exchanged product. If approved after quality check, the return or exchange request will be processed in accordance with our policies.

Shipping Policy

Orders for users are shipped through registered domestic courier companies or speed post only. Orders are shipped within 7 days from the date of order and payment, or as per the delivery date agreed at the time of order confirmation and delivery of the shipment, subject to courier company or post office norms.

The Platform Owner shall not be liable for delay in delivery by the courier company or postal authority. Delivery of all orders will be made to the address provided by the buyer at the time of purchase. Delivery of our services will be confirmed on the email ID specified at the time of registration.

If any shipping costs are levied by the seller or the Platform Owner, as applicable, such costs are not refundable.`,
  },
};

export const PolicyPage = ({ type }: { type: PolicyKey }) => {
  const policy = policies[type];

  return (
    <main className="policy-shell" style={{ minHeight: '100vh', background: 'var(--background)', color: 'var(--foreground)', padding: '48px 20px' }}>
      <section className="policy-section" style={{ maxWidth: '960px', margin: '0 auto' }}>
        <Link to="/" style={{ color: 'var(--primary)', textDecoration: 'none', fontWeight: 700 }}>
          Back to Pluto
        </Link>

        <header style={{ marginTop: '44px', marginBottom: '28px' }}>
          <p style={{ color: 'var(--text-secondary)', fontSize: '0.82rem', fontWeight: 700, letterSpacing: '0.08em', textTransform: 'uppercase', marginBottom: '12px' }}>
            {policy.updated}
          </p>
          <h1 style={{ fontSize: 'clamp(1.1rem, 3vw, 2.3rem)', lineHeight: 1, letterSpacing: '-0.03em', margin: 0 }}>
            {policy.title}
          </h1>
        </header>

        <article
          className="glass-card policy-card"
          style={{
            padding: 'clamp(24px, 5vw, 48px)',
            borderRadius: '16px',
            display: 'flex',
            flexDirection: 'column',
            gap: '18px',
          }}
        >
          {policy.body.split('\n\n').map((paragraph) => {
            const isSectionHeading = !paragraph.includes('.') && paragraph.length < 80;

            return isSectionHeading ? (
              <h2 key={paragraph} style={{ fontSize: '1.4rem', margin: '18px 0 0', color: 'var(--primary)' }}>
                {paragraph}
              </h2>
            ) : (
              <p key={paragraph} style={{ margin: 0, color: 'var(--text-secondary)', lineHeight: 1.8, fontSize: '0.98rem' }}>
                {paragraph}
              </p>
            );
          })}
        </article>
      </section>
    </main>
  );
};
